name: Format post
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update articles name
      run: |
        git diff --name-only HEAD^1 HEAD | tee | while read line ; do [[ "$line" == blog/* ]] && mv $line $(date +"%Y-%m-%d")-$line; done
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Posting new blog posts"
        git push